services:
  postgres:
    image: postgres:16
    container_name: progile-postgres
    environment:
      POSTGRES_DB: progile
      POSTGRES_USER: progile
      POSTGRES_PASSWORD: progile
    ports:
      - "5432:5432"
    volumes:
      - progile-postgres-data:/var/lib/postgresql/data

volumes:
  progile-postgres-data:
